package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"pastebin/graph/model"
)

// CreateDocument is the resolver for the createDocument field.
func (r *mutationResolver) CreateDocument(ctx context.Context, input model.CreateDocumentInput) (*int, error) {
	fmt.Println("CreateDocument mutation")
	var id, err = r.DocumentService.CreateDocument(input.Value, input.AccessKey, *input.MaxViewCount, *input.TTLMs)
	if err != nil {
		return nil, err
	}
	fmt.Printf("CreateDocument %v", id)
	return &id, nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, id int, accessKey string) (*bool, error) {
	fmt.Println("DeleteDocument mutation")
	success, err := r.DocumentService.DeleteDocument(id, accessKey)
	if err != nil {
		return nil, err
	}
	fmt.Printf("DeleteDocument %v", id)
	return &success, nil
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, input model.UpdateDocumentInput) (*bool, error) {
	success, err := r.DocumentService.UpdateDocument(input.ID, input.Value, input.AccessKey, input.MaxViewCount, input.TTLMs)
	if err != nil {
		return nil, err
	}
	return &success, nil
}

// GetDocument is the resolver for the getDocument field.
func (r *queryResolver) GetDocument(ctx context.Context, id int) (*model.Document, error) {
	fmt.Printf("GetDocument %v", id)
	return r.DocumentService.GetDocument(id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
